- name: test vbox module
  hosts: localhost
  tasks:

  - name: Run the vbox module for success
    virtualbox:
      node_ip: '172.16.77.19'
      username: vbox
      password: '#SDtBnJuUBeQa4GJq!Zhw8EVLQatsk'
    register: test_success_out
  
  - name: Debug the test_success_out
    debug:
      msg: '{{ test_success_out }}'

  # - name: Run the vbox module for fail
  #   vbox:
  #     name: 'hello'
  #     new: true
  #   register: test_fail_out
  #   ignore_errors: true
  
  # - name: Debug the test_fail_out
  #   debug:
  #     msg: '{{ test_fail_out }}'

  # - name: Run the vbox module for success
  #   vbox:
  #     node_ip: '172.16.77.19'
  #     username: vbox
  #     password: '#SDtBnJuUBeQa4GJq!Zhw8EVLQatsk'
  #   register: test_fail_success
  #   ignore_errors: true
  
  # - name: Debug the test_fail_success
  #   debug:
  #     msg: '{{ test_fail_success }}'

